# -*- mode: restclient; -*-

# Ping
GET http://localhost:3000/api/ping

# Get many documents
GET http://localhost:3000/api/documents

# Search documents by name (starting with "wo")
GET http://localhost:3000/api/documents?search=wo%25

# Get documents with a limit
GET http://localhost:3000/api/documents?limit=1

# Get documents with an offset
GET http://localhost:3000/api/documents?limit=1&offset=5

# Get a document
GET http://localhost:3000/api/documents/644

# Get global words
GET http://localhost:3000/api/words/foo

# Get local words
GET http://localhost:3000/api/documents/644/words

# Check a document for unknown words
GET http://localhost:3000/api/documents/644/check-words

# Add a local word
PUT http://localhost:3000/api/documents/644/words
Content-Type: application/json
{
  "untranslated": "hilabulaterobas",
  "grade1": "HILA",
  "grade2": "H4LA",
  "hyphenated": "hila-bula-tero-bas",
  "spelling": 1,
  "type": 0,
  "homograph-disambiguation": "",
  "document-id": 644,
  "islocal": false
}

# Delete a local word
DELETE http://localhost:3000/api/documents/644/words
Content-Type: application/json
{
  "untranslated": "hilabulaterobas",
  "grade1": "HILA",
  "grade2": "H4LA",
  "hyphenated": "hila-bula-tero-bas",
  "spelling": 1,
  "type": 0,
  "homograph-disambiguation": "",
  "document-id": 644,
  "islocal": false
}

# Get words to confirm
GET http://localhost:3000/api/confirmable?limit=10

# Confirm a word and set it to local. This should simply upsert the
# records in the db and set them to confirmed and local
PUT http://localhost:3000/api/confirmable
Content-Type: application/json
{
  "untranslated": "hilabulaterobas",
  "grade1": "HILA",
  "grade2": "H4LA",
  "hyphenated": "hila-bula-tero-bas",
  "spelling": 1,
  "type": 0,
  "homograph-disambiguation": "",
  "document-id": 644,
  "islocal": true
}

# Confirm a word. This should move the records to the global table
PUT http://localhost:3000/api/confirmable
Content-Type: application/json
{
  "untranslated": "hilabulaterobas",
  "grade1": "HILA",
  "grade2": "H4LA",
  "hyphenated": "hila-bula-tero-bas",
  "spelling": 1,
  "type": 0,
  "homograph-disambiguation": "",
  "document-id": 644,
  "islocal": false
}

